### ISSUE TITLE
Design Process / Overview of 3dio-modifiers-app

### ISSUE THREAD

**Issue by Aadjou** [archilogic-com/3dio-modifiers-app#2]
(WIP)
based on skype call with Tomas

**Phase 1**
- lean approach, courage for simplicity
- start out with preset, hardcoded list of furniture
- **Design**
 3 Columns style, simple, small section with text information, input -> output visual content
![8ef01c80-4b34-456f-ba6a-ec803d6e3f5a](https://user-images.githubusercontent.com/25610447/29527508-671b984a-8699-11e7-8768-149ce33a6790.jpg)

**Phase 2, 3, 4** Ideas

- allow user to use own furniture id / data3d key
- allow user to play with settings / setup settings in modifier API
- build 3dio extension to create buffer files form any a-frame scene
- ...

**Comment by Aadjou** [comment]
phase 1:
- [ ] missing multiple window scene (awaiting pull request  merge)
- [ ] Quota reached pretty message #7
- [ ] Merge SEO approved about text & header
- [ ] Splash with pretty demo #6

phase 2: 
- [ ] use any furniture id
- [ ] use any data3d key
- [ ] provide settings and different modifiers to play with
- [ ] prettify UI
- [ ] find solution on starting the modify (current solution: autostart)

phase 3:
- [ ] allow processing api requests from entire aframe scenes
- [ ] refactor 3dio-extensions
- [ ] pull request 3dio-extensions into 3dio-js
- [ ] (...)
